#!/bin/sh

set -e

if [ -z "$PORT" ] || [ -z "$INDIR" ] || [ -z "$OUTDIR" ]
then
  echo environment not set:
  echo "    PORT=$PORT"
  echo "   INDIR=$INDIR"
  echo "  OUTDIR=$OUTDIR"
  exit 1
fi

NOTIFY_FILE=/tmp/notify-in

start() {
  echo "btpd is starting at $(date)"
  btpd \
    --port "$PORT" \
    &
}

notify_create() {
  inotifywait \
    --monitor \
    --daemon \
    --outfile "$NOTIFY_FILE" \
    "$INDIR"
}


watch() {
  echo watching for files in "$INDIR"

  while read -r dir action file
  do
    echo "$dir $action $file"
    if [ "$action" = CREATE ]
    then
      add_torrent "$dir/$file"
    fi
  done < "$NOTIFY_FILE"
}

is_torrent() {
  btinfo "$1" > /dev/null 2&>1
}

add_torrent() {
  path=$1
  hash=$(echo "$path" | sha1sum | cut -f 1 -d ' ')
  name=$(basename "$path" | tr -d '[:space:]')
  if is_torrent "$path"
  then
    echo "btcli add -d $OUTDIR/$hash -n $name $path"
    btcli add -d "$OUTDIR/$hash" -n "$name" "$path" || err=$?
    echo "could not add torrent $path ($err)"
  else
    echo "$path" is not a torrent
  fi
}


mkfifo "$NOTIFY_FILE"
notify_create
start
watch &

child=$!
wait $child

exec "$@"
